es:
  languageName: Spanish
  contentDir: content/es
  weight: 2
  title: "Título del Sitio"
  description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Página Hija de Ejemplo"
      url: "/example-page/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
